// <auto-generated />
using Ipfs.Engine;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Ipfs.Engine.Migrations
{
    [DbContext(typeof(Repository))]
    [Migration("20180126080855_Blocks")]
    partial class Blocks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Ipfs.Engine.Cryptography.EncryptedKey", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Pem");

                    b.HasKey("Name");

                    b.ToTable("EncryptedKeys");
                });

            modelBuilder.Entity("Ipfs.Engine.Cryptography.KeyInfo", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("_Id")
                        .HasColumnName("Id");

                    b.HasKey("Name");

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("Ipfs.Engine.Repository+BlockInfo", b =>
                {
                    b.Property<string>("Cid")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("DataSize");

                    b.HasKey("Cid");

                    b.ToTable("BlockInfos");
                });

            modelBuilder.Entity("Ipfs.Engine.Repository+BlockValue", b =>
                {
                    b.Property<string>("Cid")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Data");

                    b.HasKey("Cid");

                    b.ToTable("BlockValues");
                });

            modelBuilder.Entity("Ipfs.Engine.Repository+Config", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Value");

                    b.HasKey("Name");

                    b.ToTable("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
